/*
 * Copyright 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MC56F83783
package_id: MC56F83783VLH
mcu_data: ksdk2_0
processor_version: 9.0.0
pin_labels:
- {pin_num: '3', pin_signal: GPIOC0/EXTAL/CLKIN0, label: USER_LED, identifier: EXTAL;USER_LED}
- {pin_num: '4', pin_signal: GPIOC1/XTAL, label: USER_LED_2, identifier: USER_LED_2}
- {pin_num: '18', pin_signal: GPIOC5/DACA_O/XB_IN7, label: TP9, identifier: TP9}
- {pin_num: '36', pin_signal: GPIOF0/XB_IN6/TB2, label: Motor_fault_low_effective}
- {pin_num: '31', pin_signal: GPIOC6/TA2/XB_IN3/CMP_REF/SS0_B, label: TP10, identifier: XBAR_OUT10;TP10}
- {pin_num: '42', pin_signal: GPIOF5/RXD1/XB_OUT9/PWMA_1X/PWMA_FAULT7, label: TP11, identifier: XBAR_OUT11;TP11}
- {pin_num: '50', pin_signal: GPIOF1/CLKO1/XB_IN7/CMPD_O, label: PFC_fault_high_effective}
- {pin_num: '34', pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8, label: TP7, identifier: XBAR_OUT8;TP7}
- {pin_num: '35', pin_signal: GPIOC10/MOSI0/XB_IN5/MISO0/XB_OUT9, label: TP5, identifier: XBAR_OUT9;TP5}
- {pin_num: '59', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, label: RELAY, identifier: RELAY}
- {pin_num: '58', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, label: BRAKE, identifier: BRAKE}
- {pin_num: '25', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O, label: TP8, identifier: TP8}
- {pin_num: '40', pin_signal: GPIOF3/SDA1/XB_OUT7, label: TP22, identifier: TP22}
- {pin_num: '39', pin_signal: GPIOF2/SCL1/XB_OUT6, label: TP24, identifier: TP24}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {peripheral: EVTG, signal: 'EVTG0, A', pin_signal: PWMA0_OUT_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG0, B', pin_signal: PWMA0_OUT_TRIG1}
  - {peripheral: EVTG, signal: 'EVTG0, C', pin_signal: PWMA1_OUT_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG0, D', pin_signal: PWMA1_OUT_TRIG1}
  - {peripheral: EVTG, signal: 'EVTG1, A', pin_signal: PWMA2_OUT_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG1, C', pin_signal: EVTG0_OUTA}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: EVTG1_OUTA}
  - {pin_num: '14', peripheral: ADC, signal: 'ANA, 1', pin_signal: GPIOA1/ANA1/CMPA_IN0}
  - {pin_num: '16', peripheral: ADC, signal: 'ANA, 3', pin_signal: GPIOA3/ANA3/VREFLA/CMPA_IN2}
  - {pin_num: '21', peripheral: ADC, signal: 'ANB, 4', pin_signal: GPIOB4/ANB4/CMPC_IN1}
  - {pin_num: '20', peripheral: ADC, signal: 'ANB, 5', pin_signal: GPIOB5/ANB5/CMPC_IN2}
  - {pin_num: '19', peripheral: ADC, signal: 'ANB, 6', pin_signal: GPIOB6/ANB6/CMPB_IN1}
  - {pin_num: '46', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWMA_0A/XB_OUT5}
  - {pin_num: '45', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWMA_0B/XB_OUT4}
  - {pin_num: '27', peripheral: ADC, signal: 'ANB, 2', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3}
  - {pin_num: '47', peripheral: PWMA, signal: 'B, 1', pin_signal: GPIOE2/PWMA_1B/XB_OUT6}
  - {pin_num: '48', peripheral: PWMA, signal: 'A, 1', pin_signal: GPIOE3/PWMA_1A/XB_OUT7}
  - {pin_num: '51', peripheral: PWMA, signal: 'B, 2', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8}
  - {pin_num: '52', peripheral: PWMA, signal: 'A, 2', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9}
  - {pin_num: '53', peripheral: PWMA, signal: 'B, 3', pin_signal: GPIOE6/PWMA_3B/XB_IN4/PWMB_2B/XB_OUT10}
  - {pin_num: '54', peripheral: PWMA, signal: 'A, 3', pin_signal: GPIOE7/PWMA_3A/XB_IN5/PWMB_2A/XB_OUT11}
  - {pin_num: '17', peripheral: ADC, signal: 'ANB, 7', pin_signal: GPIOB7/ANB7/CMPB_IN2}
  - {pin_num: '3', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: GPIOC0/EXTAL/CLKIN0, identifier: USER_LED, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIOF, signal: 'GPIO, 7', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, direction: OUTPUT}
  - {pin_num: '36', peripheral: PWMA, signal: 'FAULT, 0', pin_signal: GPIOF0/XB_IN6/TB2}
  - {pin_num: '50', peripheral: PWMA, signal: 'FAULT, 1', pin_signal: GPIOF1/CLKO1/XB_IN7/CMPD_O}
  - {pin_num: '7', peripheral: QSCI0, signal: RXD, pin_signal: GPIOC3/TA0/CMPA_O/RXD0/CLKIN1}
  - {pin_num: '5', peripheral: QSCI0, signal: TXD, pin_signal: GPIOC2/TXD0/TB0/XB_IN2/CLKO0}
  - {pin_num: '4', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: GPIOC1/XTAL, direction: OUTPUT}
  - {pin_num: '58', peripheral: GPIOF, signal: 'GPIO, 6', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, direction: OUTPUT}
  - {pin_num: '40', peripheral: GPIOF, signal: 'GPIO, 3', pin_signal: GPIOF3/SDA1/XB_OUT7, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '39', peripheral: GPIOF, signal: 'GPIO, 2', pin_signal: GPIOF2/SCL1/XB_OUT6, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOA1 (pin 14) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA3 (pin 16) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB2 (pin 27) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB4 (pin 21) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB5 (pin 20) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB6 (pin 19) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB7 (pin 17) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BOARD_USER_LED_GPIO, BOARD_USER_LED_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BOARD_USER_LED_2_GPIO, BOARD_USER_LED_2_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C2_TXD0);
    /* Enable peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C3_RXD0);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E0_PWMA_0B);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E1_PWMA_0A);
    /* Enable peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E2_PWMA_1B);
    /* Enable peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E3_PWMA_1A);
    /* Enable peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_PWMA_2B);
    /* Enable peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_PWMA_2A);
    /* Enable peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E6_PWMA_3B);
    /* Enable peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E7_PWMA_3A);
    /* Enable peripheral functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F0_XB_IN6);
    /* Enable peripheral functionality on pin GPIOF1 (pin 50) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF1 (pin 50) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F1_XB_IN7);
    /* GPIO functionality on pin GPIOF2 (pin 39) */
    GPIO_PinSetPeripheralMode(BOARD_TP24_GPIO, BOARD_TP24_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF3 (pin 40) */
    GPIO_PinSetPeripheralMode(BOARD_TP22_GPIO, BOARD_TP22_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF6 (pin 58) */
    GPIO_PinSetPeripheralMode(BOARD_BRAKE_GPIO, BOARD_BRAKE_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(BOARD_RELAY_GPIO, BOARD_RELAY_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinWrite(BOARD_USER_LED_GPIO, BOARD_USER_LED_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_USER_LED_GPIO, BOARD_USER_LED_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinWrite(BOARD_USER_LED_2_GPIO, BOARD_USER_LED_2_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_USER_LED_2_GPIO, BOARD_USER_LED_2_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF2 (pin 39)  */
    GPIO_PinWrite(BOARD_TP24_GPIO, BOARD_TP24_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TP24_GPIO, BOARD_TP24_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF3 (pin 40)  */
    GPIO_PinWrite(BOARD_TP22_GPIO, BOARD_TP22_PIN_MASK, kGPIO_OutputHigh);
    GPIO_PinSetDirection(BOARD_TP22_GPIO, BOARD_TP22_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF6 (pin 58)  */
    GPIO_PinWrite(BOARD_BRAKE_GPIO, BOARD_BRAKE_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_BRAKE_GPIO, BOARD_BRAKE_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinWrite(BOARD_RELAY_GPIO, BOARD_RELAY_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_RELAY_GPIO, BOARD_RELAY_PIN_MASK, kGPIO_DigitalOutput);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);
    /* Select PWMA Fault 1 Input.: Select PWMA Fault 1 Input, XB_OUT30. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault1InputIndex, kSIM_PWMAFault1Input_XB_OUT30);

    /* PWM Select */
    /* xbar input 28.: xbar input 28, PWMA0_OUT_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN28Index, kSIM_XbarIn28PWMA0OutTrig0);
    /* xbar input 29.: xbar input 29, PWMA0_OUT_TRIG1. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN29Index, kSIM_XbarIn29PWMA0OutTrig1);
    /* xbar input 30.: xbar input 30, PWMA1_OUT_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN30Index, kSIM_XbarIn30PWMA1OutTrig0);
    /* xbar input 31.: xbar input 31, PWMA1_OUT_TRIG1. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN31Index, kSIM_XbarIn31PWMA1OutTrig1);
    /* xbar input 32.: xbar input 32, PWMA2_OUT_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN32Index, kSIM_XbarIn32PWMA2OutTrig0);

    /* XB_IN6 output assigned to XBARA_IN6 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn6, kXBARA_OutputPwmaPwmbFault0);
    /* XB_IN7 output assigned to XBARA_IN7 input is connected
     * to XBARA_OUT30 output assigned to PWMA_PWMB_FAULT1 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn7, kXBARA_OutputPwmaPwmbFault1);
    /* PWMB0_MUX_PWMA0_OUT_TRIG0 output assigned to XBARA_IN28 input is connected
     * to XBARA_OUT47 output assigned to EVTG0_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb0MuxPwma0OutTrig0, kXBARA_OutputEvtg0A);
    /* PWMB0_MUX_PWMA0_OUT_TRIG1 output assigned to XBARA_IN29 input is connected
     * to XBARA_OUT48 output assigned to EVTG0_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb0MuxPwma0OutTrig1, kXBARA_OutputEvtg0B);
    /* PWMB1_MUX_PWMA1_OUT_TRIG0 output assigned to XBARA_IN30 input is connected
     * to XBARA_OUT49 output assigned to EVTG0_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb1MuxPwma1OutTrig0, kXBARA_OutputEvtg0C);
    /* PWMB1_MUX_PWMA1_OUT_TRIG1 output assigned to XBARA_IN31 input is connected
     * to XBARA_OUT50 output assigned to EVTG0_D */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb1MuxPwma1OutTrig1, kXBARA_OutputEvtg0D);
    /* PWMB2_MUX_PWMA2_OUT_TRIG0 output assigned to XBARA_IN32 input is connected
     * to XBARA_OUT51 output assigned to EVTG1_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb2MuxPwma2OutTrig0, kXBARA_OutputEvtg1A);
    /* EVTG0_OUTA output assigned to XBARA_IN40 input is connected
     * to XBARA_OUT53 output assigned to EVTG1_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outa, kXBARA_OutputEvtg1C);
    /* EVTG1_OUTA output assigned to XBARA_IN41 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg1Outa, kXBARA_OutputAdcaSync);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
